-- Migration 0048: Schema hardening — FK constraints, indexes, json→jsonb, real→numeric, master tables
-- Generated by NEXCOM v44 schema audit

-- ─── 1. json → jsonb migrations ──────────────────────────────────────────────
ALTER TABLE "profiles" ALTER COLUMN "metadata" TYPE jsonb USING "metadata"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "notifications" ALTER COLUMN "metadata" TYPE jsonb USING "metadata"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "kyc_queue" ALTER COLUMN "documents" TYPE jsonb USING "documents"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "audit_log" ALTER COLUMN "details" TYPE jsonb USING "details"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "cooperative_bulk_uploads" ALTER COLUMN "errors" TYPE jsonb USING "errors"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "cooperative_bulk_uploads" ALTER COLUMN "created_application_ids" TYPE jsonb USING "created_application_ids"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "security_events" ALTER COLUMN "metadata" TYPE jsonb USING "metadata"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "mojaloop_parties" ALTER COLUMN "supported_currencies" TYPE jsonb USING "supported_currencies"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "mojaloop_callbacks" ALTER COLUMN "payload" TYPE jsonb USING "payload"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "mojaloop_dfsps" ALTER COLUMN "currencies" TYPE jsonb USING "currencies"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "mojaloop_dead_letter" ALTER COLUMN "raw_payload" TYPE jsonb USING "raw_payload"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "dfsp_kyc_records" ALTER COLUMN "documents_provided" TYPE jsonb USING "documents_provided"::text::jsonb;
--> statement-breakpoint
ALTER TABLE "stripe_payments" ALTER COLUMN "metadata" TYPE jsonb USING "metadata"::text::jsonb;
--> statement-breakpoint

-- ─── 2. real → numeric(8,4) migrations ───────────────────────────────────────
ALTER TABLE "kyc_analysis_results" ALTER COLUMN "ocr_avg_confidence" TYPE numeric(8,4) USING "ocr_avg_confidence"::numeric;
--> statement-breakpoint
ALTER TABLE "kyc_analysis_results" ALTER COLUMN "document_authenticity_score" TYPE numeric(8,4) USING "document_authenticity_score"::numeric;
--> statement-breakpoint
ALTER TABLE "kyc_analysis_results" ALTER COLUMN "selfie_overall_score" TYPE numeric(8,4) USING "selfie_overall_score"::numeric;
--> statement-breakpoint
ALTER TABLE "kyc_analysis_results" ALTER COLUMN "passive_liveness_score" TYPE numeric(8,4) USING "passive_liveness_score"::numeric;
--> statement-breakpoint
ALTER TABLE "kyc_analysis_results" ALTER COLUMN "overall_score" TYPE numeric(8,4) USING "overall_score"::numeric;
--> statement-breakpoint

-- ─── 3. instruments master table ─────────────────────────────────────────────
CREATE TYPE "instrument_status" AS ENUM ('ACTIVE', 'SUSPENDED', 'DELISTED', 'PENDING');
--> statement-breakpoint
CREATE TYPE "instrument_asset_class" AS ENUM ('COMMODITY', 'FOREX', 'EQUITY', 'DIGITAL_ASSET', 'INDEX', 'FIXED_INCOME', 'DERIVATIVE');
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "instruments" (
  "id" serial PRIMARY KEY NOT NULL,
  "symbol" varchar(32) NOT NULL,
  "name" varchar(200) NOT NULL,
  "asset_class" "instrument_asset_class" NOT NULL,
  "base_currency" varchar(8) NOT NULL DEFAULT 'NGN',
  "quote_currency" varchar(8) NOT NULL DEFAULT 'NGN',
  "lot_size" numeric(18,6) NOT NULL DEFAULT '1',
  "min_lot_size" numeric(18,6) NOT NULL DEFAULT '1',
  "tick_size" numeric(18,6) NOT NULL DEFAULT '0.01',
  "price_band_pct" numeric(8,4) DEFAULT '10',
  "settlement_days" integer NOT NULL DEFAULT 2,
  "trading_hours_start" varchar(8) DEFAULT '09:30',
  "trading_hours_end" varchar(8) DEFAULT '16:00',
  "exchange" varchar(64) DEFAULT 'NEXCOM',
  "isin" varchar(20),
  "description" text,
  "status" "instrument_status" NOT NULL DEFAULT 'ACTIVE',
  "listed_at" timestamp DEFAULT now(),
  "delisted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "instruments_symbol_unique" UNIQUE("symbol")
);
--> statement-breakpoint

-- ─── 4. warehouses master table ──────────────────────────────────────────────
CREATE TYPE "warehouse_accreditation_status" AS ENUM ('PENDING', 'ACCREDITED', 'SUSPENDED', 'REVOKED');
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "warehouses" (
  "id" serial PRIMARY KEY NOT NULL,
  "name" varchar(200) NOT NULL,
  "code" varchar(32) NOT NULL,
  "operator_id" integer,
  "address" text,
  "city" varchar(100),
  "state" varchar(100),
  "country" varchar(64) DEFAULT 'Nigeria',
  "gps_lat" numeric(10,7),
  "gps_lng" numeric(10,7),
  "capacity_mt" numeric(14,2),
  "available_capacity_mt" numeric(14,2),
  "accreditation_status" "warehouse_accreditation_status" NOT NULL DEFAULT 'PENDING',
  "accreditation_ref" varchar(100),
  "accreditation_expiry" timestamp,
  "phone" varchar(32),
  "email" varchar(128),
  "supported_commodities" jsonb,
  "insurance_policy_ref" varchar(100),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "warehouses_code_unique" UNIQUE("code")
);
--> statement-breakpoint

-- ─── 5. Composite unique constraints ─────────────────────────────────────────
ALTER TABLE "positions" ADD CONSTRAINT "positions_user_symbol_unique" UNIQUE ("user_id", "symbol", "asset_class");
--> statement-breakpoint
ALTER TABLE "watchlist" ADD CONSTRAINT "watchlist_user_symbol_unique" UNIQUE ("user_id", "symbol");
--> statement-breakpoint
ALTER TABLE "order_book_levels" ADD CONSTRAINT "order_book_levels_symbol_side_price_unique" UNIQUE ("symbol", "side", "price");
--> statement-breakpoint
ALTER TABLE "commodity_indexes" ADD CONSTRAINT "commodity_indexes_symbol_unique" UNIQUE ("symbol");
--> statement-breakpoint
ALTER TABLE "live_prices" ADD CONSTRAINT "live_prices_symbol_unique" UNIQUE ("symbol");
--> statement-breakpoint

-- ─── 6. Check constraints ─────────────────────────────────────────────────────
ALTER TABLE "orders" ADD CONSTRAINT "orders_quantity_positive" CHECK ("quantity" > 0);
--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_price_positive" CHECK ("price" IS NULL OR "price" > 0);
--> statement-breakpoint
ALTER TABLE "positions" ADD CONSTRAINT "positions_quantity_nonneg" CHECK ("quantity" >= 0);
--> statement-breakpoint
ALTER TABLE "margin_calls" ADD CONSTRAINT "margin_calls_amount_positive" CHECK ("amount_required" > 0);
--> statement-breakpoint
ALTER TABLE "mojaloop_fee_schedules" ADD CONSTRAINT "fee_pct_range" CHECK ("percentage_fee" >= 0 AND "percentage_fee" <= 1);
--> statement-breakpoint
ALTER TABLE "kyc_analysis_results" ADD CONSTRAINT "score_range" CHECK ("overall_score" IS NULL OR ("overall_score" >= 0 AND "overall_score" <= 1));
--> statement-breakpoint

-- ─── 7. Performance indexes ───────────────────────────────────────────────────
-- orders
CREATE INDEX CONCURRENTLY IF NOT EXISTS "orders_user_id_idx" ON "orders" ("user_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "orders_symbol_status_idx" ON "orders" ("symbol", "status");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "orders_created_at_idx" ON "orders" ("created_at" DESC);
--> statement-breakpoint
-- trade_fills
CREATE INDEX CONCURRENTLY IF NOT EXISTS "trade_fills_order_id_idx" ON "trade_fills" ("order_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "trade_fills_user_id_created_idx" ON "trade_fills" ("user_id", "created_at" DESC);
--> statement-breakpoint
-- settlements
CREATE INDEX CONCURRENTLY IF NOT EXISTS "settlements_user_id_status_idx" ON "settlements" ("user_id", "status");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "settlements_created_at_idx" ON "settlements" ("created_at" DESC);
--> statement-breakpoint
-- notifications
CREATE INDEX CONCURRENTLY IF NOT EXISTS "notifications_user_id_read_idx" ON "notifications" ("user_id", "read");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "notifications_created_at_idx" ON "notifications" ("created_at" DESC);
--> statement-breakpoint
-- positions
CREATE INDEX CONCURRENTLY IF NOT EXISTS "positions_user_id_idx" ON "positions" ("user_id");
--> statement-breakpoint
-- warehouse_receipts
CREATE INDEX CONCURRENTLY IF NOT EXISTS "warehouse_receipts_user_id_idx" ON "warehouse_receipts" ("user_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "warehouse_receipts_status_idx" ON "warehouse_receipts" ("status");
--> statement-breakpoint
-- aml_flags
CREATE INDEX CONCURRENTLY IF NOT EXISTS "aml_flags_user_id_idx" ON "aml_flags" ("user_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "aml_flags_status_flagged_idx" ON "aml_flags" ("status", "flagged_at" DESC);
--> statement-breakpoint
-- kyc_queue
CREATE INDEX CONCURRENTLY IF NOT EXISTS "kyc_queue_user_id_idx" ON "kyc_queue" ("user_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "kyc_queue_status_idx" ON "kyc_queue" ("status");
--> statement-breakpoint
-- audit_log
CREATE INDEX CONCURRENTLY IF NOT EXISTS "audit_log_user_id_idx" ON "audit_log" ("user_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "audit_log_action_created_idx" ON "audit_log" ("action", "created_at" DESC);
--> statement-breakpoint
-- margin_calls
CREATE INDEX CONCURRENTLY IF NOT EXISTS "margin_calls_user_id_status_idx" ON "margin_calls" ("user_id", "status");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "margin_calls_due_at_idx" ON "margin_calls" ("due_at");
--> statement-breakpoint
-- bank_transactions
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_transactions_user_id_idx" ON "bank_transactions" ("user_id");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "bank_transactions_created_at_idx" ON "bank_transactions" ("created_at" DESC);
--> statement-breakpoint
-- price_alerts
CREATE INDEX CONCURRENTLY IF NOT EXISTS "price_alerts_user_id_idx" ON "price_alerts" ("user_id");
--> statement-breakpoint
-- kyc_analysis_results
CREATE INDEX CONCURRENTLY IF NOT EXISTS "kyc_analysis_user_id_idx" ON "kyc_analysis_results" ("user_id");
--> statement-breakpoint
-- mojaloop_transfers
CREATE INDEX CONCURRENTLY IF NOT EXISTS "mojaloop_transfers_status_idx" ON "mojaloop_transfers" ("status");
--> statement-breakpoint
-- loan_lifecycle_events
CREATE INDEX CONCURRENTLY IF NOT EXISTS "loan_events_loan_id_idx" ON "loan_lifecycle_events" ("loan_id");
--> statement-breakpoint
-- sar_reports
CREATE INDEX CONCURRENTLY IF NOT EXISTS "sar_reports_user_id_idx" ON "sar_reports" ("user_id");
--> statement-breakpoint
-- instruments
CREATE INDEX CONCURRENTLY IF NOT EXISTS "instruments_asset_class_status_idx" ON "instruments" ("asset_class", "status");
--> statement-breakpoint
-- warehouses
CREATE INDEX CONCURRENTLY IF NOT EXISTS "warehouses_state_idx" ON "warehouses" ("state");
--> statement-breakpoint
CREATE INDEX CONCURRENTLY IF NOT EXISTS "warehouses_accreditation_idx" ON "warehouses" ("accreditation_status");
--> statement-breakpoint

-- ─── 8. FK constraints for core relationships ────────────────────────────────
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "trade_fills" ADD CONSTRAINT "trade_fills_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "positions" ADD CONSTRAINT "positions_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "kyc_queue" ADD CONSTRAINT "kyc_queue_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "margin_accounts" ADD CONSTRAINT "margin_accounts_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "clearing_accounts" ADD CONSTRAINT "clearing_accounts_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "warehouse_receipts" ADD CONSTRAINT "warehouse_receipts_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "aml_flags" ADD CONSTRAINT "aml_flags_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "sar_reports" ADD CONSTRAINT "sar_reports_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "device_sessions" ADD CONSTRAINT "device_sessions_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "webauthn_credentials" ADD CONSTRAINT "webauthn_credentials_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "user_mfa_settings" ADD CONSTRAINT "user_mfa_settings_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
--> statement-breakpoint
ALTER TABLE "bank_accounts" ADD CONSTRAINT "bank_accounts_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "stripe_payments" ADD CONSTRAINT "stripe_payments_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "crop_insurance_policies" ADD CONSTRAINT "crop_insurance_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;
--> statement-breakpoint
ALTER TABLE "warehouse_receipts" ADD CONSTRAINT "warehouse_receipts_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE RESTRICT;