// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/indices.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommodityIndicesService_GetIndex_FullMethodName          = "/nexcom.indices.v1.CommodityIndicesService/GetIndex"
	CommodityIndicesService_GetAllIndices_FullMethodName     = "/nexcom.indices.v1.CommodityIndicesService/GetAllIndices"
	CommodityIndicesService_GetIndexHistory_FullMethodName   = "/nexcom.indices.v1.CommodityIndicesService/GetIndexHistory"
	CommodityIndicesService_StreamIndex_FullMethodName       = "/nexcom.indices.v1.CommodityIndicesService/StreamIndex"
	CommodityIndicesService_GetCommodityPrice_FullMethodName = "/nexcom.indices.v1.CommodityIndicesService/GetCommodityPrice"
	CommodityIndicesService_GetMarketSummary_FullMethodName  = "/nexcom.indices.v1.CommodityIndicesService/GetMarketSummary"
	CommodityIndicesService_CalculateBasket_FullMethodName   = "/nexcom.indices.v1.CommodityIndicesService/CalculateBasket"
)

// CommodityIndicesServiceClient is the client API for CommodityIndicesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommodityIndicesService provides real-time and historical commodity
// price indices for the NEXCOM Exchange platform.
type CommodityIndicesServiceClient interface {
	// GetIndex returns the current value of a named index
	GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexResponse, error)
	// GetAllIndices returns all active indices
	GetAllIndices(ctx context.Context, in *GetAllIndicesRequest, opts ...grpc.CallOption) (*GetAllIndicesResponse, error)
	// GetIndexHistory returns historical values for an index
	GetIndexHistory(ctx context.Context, in *GetIndexHistoryRequest, opts ...grpc.CallOption) (*GetIndexHistoryResponse, error)
	// StreamIndex streams live index updates
	StreamIndex(ctx context.Context, in *StreamIndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexUpdate], error)
	// GetCommodityPrice returns the current price for a commodity
	GetCommodityPrice(ctx context.Context, in *GetCommodityPriceRequest, opts ...grpc.CallOption) (*GetCommodityPriceResponse, error)
	// GetMarketSummary returns a market summary for all commodities
	GetMarketSummary(ctx context.Context, in *GetMarketSummaryRequest, opts ...grpc.CallOption) (*GetMarketSummaryResponse, error)
	// CalculateBasket calculates a custom basket index
	CalculateBasket(ctx context.Context, in *CalculateBasketRequest, opts ...grpc.CallOption) (*CalculateBasketResponse, error)
}

type commodityIndicesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommodityIndicesServiceClient(cc grpc.ClientConnInterface) CommodityIndicesServiceClient {
	return &commodityIndicesServiceClient{cc}
}

func (c *commodityIndicesServiceClient) GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexResponse)
	err := c.cc.Invoke(ctx, CommodityIndicesService_GetIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commodityIndicesServiceClient) GetAllIndices(ctx context.Context, in *GetAllIndicesRequest, opts ...grpc.CallOption) (*GetAllIndicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllIndicesResponse)
	err := c.cc.Invoke(ctx, CommodityIndicesService_GetAllIndices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commodityIndicesServiceClient) GetIndexHistory(ctx context.Context, in *GetIndexHistoryRequest, opts ...grpc.CallOption) (*GetIndexHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexHistoryResponse)
	err := c.cc.Invoke(ctx, CommodityIndicesService_GetIndexHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commodityIndicesServiceClient) StreamIndex(ctx context.Context, in *StreamIndexRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommodityIndicesService_ServiceDesc.Streams[0], CommodityIndicesService_StreamIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamIndexRequest, IndexUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommodityIndicesService_StreamIndexClient = grpc.ServerStreamingClient[IndexUpdate]

func (c *commodityIndicesServiceClient) GetCommodityPrice(ctx context.Context, in *GetCommodityPriceRequest, opts ...grpc.CallOption) (*GetCommodityPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommodityPriceResponse)
	err := c.cc.Invoke(ctx, CommodityIndicesService_GetCommodityPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commodityIndicesServiceClient) GetMarketSummary(ctx context.Context, in *GetMarketSummaryRequest, opts ...grpc.CallOption) (*GetMarketSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketSummaryResponse)
	err := c.cc.Invoke(ctx, CommodityIndicesService_GetMarketSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commodityIndicesServiceClient) CalculateBasket(ctx context.Context, in *CalculateBasketRequest, opts ...grpc.CallOption) (*CalculateBasketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateBasketResponse)
	err := c.cc.Invoke(ctx, CommodityIndicesService_CalculateBasket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommodityIndicesServiceServer is the server API for CommodityIndicesService service.
// All implementations must embed UnimplementedCommodityIndicesServiceServer
// for forward compatibility.
//
// CommodityIndicesService provides real-time and historical commodity
// price indices for the NEXCOM Exchange platform.
type CommodityIndicesServiceServer interface {
	// GetIndex returns the current value of a named index
	GetIndex(context.Context, *GetIndexRequest) (*GetIndexResponse, error)
	// GetAllIndices returns all active indices
	GetAllIndices(context.Context, *GetAllIndicesRequest) (*GetAllIndicesResponse, error)
	// GetIndexHistory returns historical values for an index
	GetIndexHistory(context.Context, *GetIndexHistoryRequest) (*GetIndexHistoryResponse, error)
	// StreamIndex streams live index updates
	StreamIndex(*StreamIndexRequest, grpc.ServerStreamingServer[IndexUpdate]) error
	// GetCommodityPrice returns the current price for a commodity
	GetCommodityPrice(context.Context, *GetCommodityPriceRequest) (*GetCommodityPriceResponse, error)
	// GetMarketSummary returns a market summary for all commodities
	GetMarketSummary(context.Context, *GetMarketSummaryRequest) (*GetMarketSummaryResponse, error)
	// CalculateBasket calculates a custom basket index
	CalculateBasket(context.Context, *CalculateBasketRequest) (*CalculateBasketResponse, error)
	mustEmbedUnimplementedCommodityIndicesServiceServer()
}

// UnimplementedCommodityIndicesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommodityIndicesServiceServer struct{}

func (UnimplementedCommodityIndicesServiceServer) GetIndex(context.Context, *GetIndexRequest) (*GetIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndex not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) GetAllIndices(context.Context, *GetAllIndicesRequest) (*GetAllIndicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllIndices not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) GetIndexHistory(context.Context, *GetIndexHistoryRequest) (*GetIndexHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexHistory not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) StreamIndex(*StreamIndexRequest, grpc.ServerStreamingServer[IndexUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamIndex not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) GetCommodityPrice(context.Context, *GetCommodityPriceRequest) (*GetCommodityPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommodityPrice not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) GetMarketSummary(context.Context, *GetMarketSummaryRequest) (*GetMarketSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketSummary not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) CalculateBasket(context.Context, *CalculateBasketRequest) (*CalculateBasketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBasket not implemented")
}
func (UnimplementedCommodityIndicesServiceServer) mustEmbedUnimplementedCommodityIndicesServiceServer() {
}
func (UnimplementedCommodityIndicesServiceServer) testEmbeddedByValue() {}

// UnsafeCommodityIndicesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommodityIndicesServiceServer will
// result in compilation errors.
type UnsafeCommodityIndicesServiceServer interface {
	mustEmbedUnimplementedCommodityIndicesServiceServer()
}

func RegisterCommodityIndicesServiceServer(s grpc.ServiceRegistrar, srv CommodityIndicesServiceServer) {
	// If the following call panics, it indicates UnimplementedCommodityIndicesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommodityIndicesService_ServiceDesc, srv)
}

func _CommodityIndicesService_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommodityIndicesServiceServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommodityIndicesService_GetIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommodityIndicesServiceServer).GetIndex(ctx, req.(*GetIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommodityIndicesService_GetAllIndices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllIndicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommodityIndicesServiceServer).GetAllIndices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommodityIndicesService_GetAllIndices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommodityIndicesServiceServer).GetAllIndices(ctx, req.(*GetAllIndicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommodityIndicesService_GetIndexHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommodityIndicesServiceServer).GetIndexHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommodityIndicesService_GetIndexHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommodityIndicesServiceServer).GetIndexHistory(ctx, req.(*GetIndexHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommodityIndicesService_StreamIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamIndexRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommodityIndicesServiceServer).StreamIndex(m, &grpc.GenericServerStream[StreamIndexRequest, IndexUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommodityIndicesService_StreamIndexServer = grpc.ServerStreamingServer[IndexUpdate]

func _CommodityIndicesService_GetCommodityPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommodityPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommodityIndicesServiceServer).GetCommodityPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommodityIndicesService_GetCommodityPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommodityIndicesServiceServer).GetCommodityPrice(ctx, req.(*GetCommodityPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommodityIndicesService_GetMarketSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommodityIndicesServiceServer).GetMarketSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommodityIndicesService_GetMarketSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommodityIndicesServiceServer).GetMarketSummary(ctx, req.(*GetMarketSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommodityIndicesService_CalculateBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommodityIndicesServiceServer).CalculateBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommodityIndicesService_CalculateBasket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommodityIndicesServiceServer).CalculateBasket(ctx, req.(*CalculateBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommodityIndicesService_ServiceDesc is the grpc.ServiceDesc for CommodityIndicesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommodityIndicesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexcom.indices.v1.CommodityIndicesService",
	HandlerType: (*CommodityIndicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndex",
			Handler:    _CommodityIndicesService_GetIndex_Handler,
		},
		{
			MethodName: "GetAllIndices",
			Handler:    _CommodityIndicesService_GetAllIndices_Handler,
		},
		{
			MethodName: "GetIndexHistory",
			Handler:    _CommodityIndicesService_GetIndexHistory_Handler,
		},
		{
			MethodName: "GetCommodityPrice",
			Handler:    _CommodityIndicesService_GetCommodityPrice_Handler,
		},
		{
			MethodName: "GetMarketSummary",
			Handler:    _CommodityIndicesService_GetMarketSummary_Handler,
		},
		{
			MethodName: "CalculateBasket",
			Handler:    _CommodityIndicesService_CalculateBasket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIndex",
			Handler:       _CommodityIndicesService_StreamIndex_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/indices.proto",
}
