// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/indices.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Index represents a commodity price index
type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Change        float64                `protobuf:"fixed64,5,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,6,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	High          float64                `protobuf:"fixed64,7,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,8,opt,name=low,proto3" json:"low,omitempty"`
	Open          float64                `protobuf:"fixed64,9,opt,name=open,proto3" json:"open,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Currency      string                 `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	BaseDate      string                 `protobuf:"bytes,12,opt,name=base_date,json=baseDate,proto3" json:"base_date,omitempty"`
	BaseValue     float64                `protobuf:"fixed64,13,opt,name=base_value,json=baseValue,proto3" json:"base_value,omitempty"`
	Components    []string               `protobuf:"bytes,14,rep,name=components,proto3" json:"components,omitempty"`
	Methodology   string                 `protobuf:"bytes,15,opt,name=methodology,proto3" json:"methodology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_proto_indices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{0}
}

func (x *Index) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Index) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Index) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Index) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *Index) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Index) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Index) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Index) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Index) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Index) GetBaseDate() string {
	if x != nil {
		return x.BaseDate
	}
	return ""
}

func (x *Index) GetBaseValue() float64 {
	if x != nil {
		return x.BaseValue
	}
	return 0
}

func (x *Index) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Index) GetMethodology() string {
	if x != nil {
		return x.Methodology
	}
	return ""
}

// CommodityPrice represents the current price of a commodity
type CommodityPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Bid           float64                `protobuf:"fixed64,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64                `protobuf:"fixed64,5,opt,name=ask,proto3" json:"ask,omitempty"`
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	Open          float64                `protobuf:"fixed64,8,opt,name=open,proto3" json:"open,omitempty"`
	Close         float64                `protobuf:"fixed64,9,opt,name=close,proto3" json:"close,omitempty"`
	Change        float64                `protobuf:"fixed64,10,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,11,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Volume        float64                `protobuf:"fixed64,12,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     int64                  `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Currency      string                 `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	Unit          string                 `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`
	Exchange      string                 `protobuf:"bytes,16,opt,name=exchange,proto3" json:"exchange,omitempty"`
	QualityGrade  string                 `protobuf:"bytes,17,opt,name=quality_grade,json=qualityGrade,proto3" json:"quality_grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommodityPrice) Reset() {
	*x = CommodityPrice{}
	mi := &file_proto_indices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommodityPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommodityPrice) ProtoMessage() {}

func (x *CommodityPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommodityPrice.ProtoReflect.Descriptor instead.
func (*CommodityPrice) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{1}
}

func (x *CommodityPrice) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CommodityPrice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommodityPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CommodityPrice) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *CommodityPrice) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *CommodityPrice) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CommodityPrice) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CommodityPrice) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CommodityPrice) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CommodityPrice) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *CommodityPrice) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *CommodityPrice) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CommodityPrice) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CommodityPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CommodityPrice) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CommodityPrice) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CommodityPrice) GetQualityGrade() string {
	if x != nil {
		return x.QualityGrade
	}
	return ""
}

// HistoricalDataPoint represents a single historical data point
type HistoricalDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalDataPoint) Reset() {
	*x = HistoricalDataPoint{}
	mi := &file_proto_indices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalDataPoint) ProtoMessage() {}

func (x *HistoricalDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalDataPoint.ProtoReflect.Descriptor instead.
func (*HistoricalDataPoint) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{2}
}

func (x *HistoricalDataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HistoricalDataPoint) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *HistoricalDataPoint) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *HistoricalDataPoint) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *HistoricalDataPoint) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *HistoricalDataPoint) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// IndexUpdate is a streaming update for an index
type IndexUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Change        float64                `protobuf:"fixed64,3,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexUpdate) Reset() {
	*x = IndexUpdate{}
	mi := &file_proto_indices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexUpdate) ProtoMessage() {}

func (x *IndexUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexUpdate.ProtoReflect.Descriptor instead.
func (*IndexUpdate) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{3}
}

func (x *IndexUpdate) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *IndexUpdate) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IndexUpdate) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *IndexUpdate) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *IndexUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// BasketComponent defines a component of a custom basket
type BasketComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketComponent) Reset() {
	*x = BasketComponent{}
	mi := &file_proto_indices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketComponent) ProtoMessage() {}

func (x *BasketComponent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketComponent.ProtoReflect.Descriptor instead.
func (*BasketComponent) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{4}
}

func (x *BasketComponent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BasketComponent) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// MarketSummaryItem represents a single item in the market summary
type MarketSummaryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Trend         string                 `protobuf:"bytes,6,opt,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketSummaryItem) Reset() {
	*x = MarketSummaryItem{}
	mi := &file_proto_indices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketSummaryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketSummaryItem) ProtoMessage() {}

func (x *MarketSummaryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketSummaryItem.ProtoReflect.Descriptor instead.
func (*MarketSummaryItem) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{5}
}

func (x *MarketSummaryItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketSummaryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketSummaryItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketSummaryItem) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *MarketSummaryItem) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MarketSummaryItem) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

type GetIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexRequest) Reset() {
	*x = GetIndexRequest{}
	mi := &file_proto_indices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequest) ProtoMessage() {}

func (x *GetIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequest.ProtoReflect.Descriptor instead.
func (*GetIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{6}
}

func (x *GetIndexRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

type GetIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *Index                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexResponse) Reset() {
	*x = GetIndexResponse{}
	mi := &file_proto_indices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexResponse) ProtoMessage() {}

func (x *GetIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexResponse.ProtoReflect.Descriptor instead.
func (*GetIndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{7}
}

func (x *GetIndexResponse) GetIndex() *Index {
	if x != nil {
		return x.Index
	}
	return nil
}

type GetAllIndicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // optional filter: "GRAIN", "OILSEED", "CASH_CROP", "COMPOSITE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllIndicesRequest) Reset() {
	*x = GetAllIndicesRequest{}
	mi := &file_proto_indices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllIndicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllIndicesRequest) ProtoMessage() {}

func (x *GetAllIndicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllIndicesRequest.ProtoReflect.Descriptor instead.
func (*GetAllIndicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllIndicesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetAllIndicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []*Index               `protobuf:"bytes,1,rep,name=indices,proto3" json:"indices,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllIndicesResponse) Reset() {
	*x = GetAllIndicesResponse{}
	mi := &file_proto_indices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllIndicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllIndicesResponse) ProtoMessage() {}

func (x *GetAllIndicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllIndicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllIndicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllIndicesResponse) GetIndices() []*Index {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *GetAllIndicesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetIndexHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"` // "1H", "4H", "1D", "1W", "1M", "1Y"
	FromTimestamp int64                  `protobuf:"varint,3,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	ToTimestamp   int64                  `protobuf:"varint,4,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexHistoryRequest) Reset() {
	*x = GetIndexHistoryRequest{}
	mi := &file_proto_indices_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexHistoryRequest) ProtoMessage() {}

func (x *GetIndexHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetIndexHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{10}
}

func (x *GetIndexHistoryRequest) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *GetIndexHistoryRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetIndexHistoryRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *GetIndexHistoryRequest) GetToTimestamp() int64 {
	if x != nil {
		return x.ToTimestamp
	}
	return 0
}

func (x *GetIndexHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetIndexHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexId       string                 `protobuf:"bytes,1,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	Data          []*HistoricalDataPoint `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexHistoryResponse) Reset() {
	*x = GetIndexHistoryResponse{}
	mi := &file_proto_indices_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexHistoryResponse) ProtoMessage() {}

func (x *GetIndexHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetIndexHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{11}
}

func (x *GetIndexHistoryResponse) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *GetIndexHistoryResponse) GetData() []*HistoricalDataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamIndexRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IndexIds        []string               `protobuf:"bytes,1,rep,name=index_ids,json=indexIds,proto3" json:"index_ids,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamIndexRequest) Reset() {
	*x = StreamIndexRequest{}
	mi := &file_proto_indices_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIndexRequest) ProtoMessage() {}

func (x *StreamIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIndexRequest.ProtoReflect.Descriptor instead.
func (*StreamIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{12}
}

func (x *StreamIndexRequest) GetIndexIds() []string {
	if x != nil {
		return x.IndexIds
	}
	return nil
}

func (x *StreamIndexRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type GetCommodityPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommodityPriceRequest) Reset() {
	*x = GetCommodityPriceRequest{}
	mi := &file_proto_indices_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommodityPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommodityPriceRequest) ProtoMessage() {}

func (x *GetCommodityPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommodityPriceRequest.ProtoReflect.Descriptor instead.
func (*GetCommodityPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommodityPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetCommodityPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *CommodityPrice        `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommodityPriceResponse) Reset() {
	*x = GetCommodityPriceResponse{}
	mi := &file_proto_indices_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommodityPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommodityPriceResponse) ProtoMessage() {}

func (x *GetCommodityPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommodityPriceResponse.ProtoReflect.Descriptor instead.
func (*GetCommodityPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommodityPriceResponse) GetPrice() *CommodityPrice {
	if x != nil {
		return x.Price
	}
	return nil
}

type GetMarketSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // optional
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketSummaryRequest) Reset() {
	*x = GetMarketSummaryRequest{}
	mi := &file_proto_indices_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketSummaryRequest) ProtoMessage() {}

func (x *GetMarketSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetMarketSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{15}
}

func (x *GetMarketSummaryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetMarketSummaryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMarketSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MarketSummaryItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Gainers       int32                  `protobuf:"varint,2,opt,name=gainers,proto3" json:"gainers,omitempty"`
	Losers        int32                  `protobuf:"varint,3,opt,name=losers,proto3" json:"losers,omitempty"`
	Unchanged     int32                  `protobuf:"varint,4,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketSummaryResponse) Reset() {
	*x = GetMarketSummaryResponse{}
	mi := &file_proto_indices_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketSummaryResponse) ProtoMessage() {}

func (x *GetMarketSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetMarketSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{16}
}

func (x *GetMarketSummaryResponse) GetItems() []*MarketSummaryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetMarketSummaryResponse) GetGainers() int32 {
	if x != nil {
		return x.Gainers
	}
	return 0
}

func (x *GetMarketSummaryResponse) GetLosers() int32 {
	if x != nil {
		return x.Losers
	}
	return 0
}

func (x *GetMarketSummaryResponse) GetUnchanged() int32 {
	if x != nil {
		return x.Unchanged
	}
	return 0
}

func (x *GetMarketSummaryResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CalculateBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Components    []*BasketComponent     `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateBasketRequest) Reset() {
	*x = CalculateBasketRequest{}
	mi := &file_proto_indices_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateBasketRequest) ProtoMessage() {}

func (x *CalculateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateBasketRequest.ProtoReflect.Descriptor instead.
func (*CalculateBasketRequest) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{17}
}

func (x *CalculateBasketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CalculateBasketRequest) GetComponents() []*BasketComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *CalculateBasketRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CalculateBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,3,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Components    []*BasketComponent     `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateBasketResponse) Reset() {
	*x = CalculateBasketResponse{}
	mi := &file_proto_indices_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateBasketResponse) ProtoMessage() {}

func (x *CalculateBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_indices_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateBasketResponse.ProtoReflect.Descriptor instead.
func (*CalculateBasketResponse) Descriptor() ([]byte, []int) {
	return file_proto_indices_proto_rawDescGZIP(), []int{18}
}

func (x *CalculateBasketResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CalculateBasketResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CalculateBasketResponse) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *CalculateBasketResponse) GetComponents() []*BasketComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *CalculateBasketResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_indices_proto protoreflect.FileDescriptor

const file_proto_indices_proto_rawDesc = "" +
	"\n" +
	"\x13proto/indices.proto\x12\x11nexcom.indices.v1\"\x94\x03\n" +
	"\x05Index\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x16\n" +
	"\x06change\x18\x05 \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\x06 \x01(\x01R\rchangePercent\x12\x12\n" +
	"\x04high\x18\a \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\b \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\t \x01(\x01R\x04open\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12\x1b\n" +
	"\tbase_date\x18\f \x01(\tR\bbaseDate\x12\x1d\n" +
	"\n" +
	"base_value\x18\r \x01(\x01R\tbaseValue\x12\x1e\n" +
	"\n" +
	"components\x18\x0e \x03(\tR\n" +
	"components\x12 \n" +
	"\vmethodology\x18\x0f \x01(\tR\vmethodology\"\xac\x03\n" +
	"\x0eCommodityPrice\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\x01R\x03ask\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\b \x01(\x01R\x04open\x12\x14\n" +
	"\x05close\x18\t \x01(\x01R\x05close\x12\x16\n" +
	"\x06change\x18\n" +
	" \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\v \x01(\x01R\rchangePercent\x12\x16\n" +
	"\x06volume\x18\f \x01(\x01R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bcurrency\x18\x0e \x01(\tR\bcurrency\x12\x12\n" +
	"\x04unit\x18\x0f \x01(\tR\x04unit\x12\x1a\n" +
	"\bexchange\x18\x10 \x01(\tR\bexchange\x12#\n" +
	"\rquality_grade\x18\x11 \x01(\tR\fqualityGrade\"\x9b\x01\n" +
	"\x13HistoricalDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\x9b\x01\n" +
	"\vIndexUpdate\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x16\n" +
	"\x06change\x18\x03 \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"A\n" +
	"\x0fBasketComponent\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"\xaa\x01\n" +
	"\x11MarketSummaryItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x14\n" +
	"\x05trend\x18\x06 \x01(\tR\x05trend\",\n" +
	"\x0fGetIndexRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\"B\n" +
	"\x10GetIndexResponse\x12.\n" +
	"\x05index\x18\x01 \x01(\v2\x18.nexcom.indices.v1.IndexR\x05index\"2\n" +
	"\x14GetAllIndicesRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"i\n" +
	"\x15GetAllIndicesResponse\x122\n" +
	"\aindices\x18\x01 \x03(\v2\x18.nexcom.indices.v1.IndexR\aindices\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xb1\x01\n" +
	"\x16GetIndexHistoryRequest\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12%\n" +
	"\x0efrom_timestamp\x18\x03 \x01(\x03R\rfromTimestamp\x12!\n" +
	"\fto_timestamp\x18\x04 \x01(\x03R\vtoTimestamp\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"p\n" +
	"\x17GetIndexHistoryResponse\x12\x19\n" +
	"\bindex_id\x18\x01 \x01(\tR\aindexId\x12:\n" +
	"\x04data\x18\x02 \x03(\v2&.nexcom.indices.v1.HistoricalDataPointR\x04data\"\\\n" +
	"\x12StreamIndexRequest\x12\x1b\n" +
	"\tindex_ids\x18\x01 \x03(\tR\bindexIds\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"2\n" +
	"\x18GetCommodityPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"T\n" +
	"\x19GetCommodityPriceResponse\x127\n" +
	"\x05price\x18\x01 \x01(\v2!.nexcom.indices.v1.CommodityPriceR\x05price\"K\n" +
	"\x17GetMarketSummaryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xc4\x01\n" +
	"\x18GetMarketSummaryResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.nexcom.indices.v1.MarketSummaryItemR\x05items\x12\x18\n" +
	"\againers\x18\x02 \x01(\x05R\againers\x12\x16\n" +
	"\x06losers\x18\x03 \x01(\x05R\x06losers\x12\x1c\n" +
	"\tunchanged\x18\x04 \x01(\x05R\tunchanged\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x8c\x01\n" +
	"\x16CalculateBasketRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\".nexcom.indices.v1.BasketComponentR\n" +
	"components\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xcc\x01\n" +
	"\x17CalculateBasketResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12%\n" +
	"\x0echange_percent\x18\x03 \x01(\x01R\rchangePercent\x12B\n" +
	"\n" +
	"components\x18\x04 \x03(\v2\".nexcom.indices.v1.BasketComponentR\n" +
	"components\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\xdb\x05\n" +
	"\x17CommodityIndicesService\x12S\n" +
	"\bGetIndex\x12\".nexcom.indices.v1.GetIndexRequest\x1a#.nexcom.indices.v1.GetIndexResponse\x12b\n" +
	"\rGetAllIndices\x12'.nexcom.indices.v1.GetAllIndicesRequest\x1a(.nexcom.indices.v1.GetAllIndicesResponse\x12h\n" +
	"\x0fGetIndexHistory\x12).nexcom.indices.v1.GetIndexHistoryRequest\x1a*.nexcom.indices.v1.GetIndexHistoryResponse\x12V\n" +
	"\vStreamIndex\x12%.nexcom.indices.v1.StreamIndexRequest\x1a\x1e.nexcom.indices.v1.IndexUpdate0\x01\x12n\n" +
	"\x11GetCommodityPrice\x12+.nexcom.indices.v1.GetCommodityPriceRequest\x1a,.nexcom.indices.v1.GetCommodityPriceResponse\x12k\n" +
	"\x10GetMarketSummary\x12*.nexcom.indices.v1.GetMarketSummaryRequest\x1a+.nexcom.indices.v1.GetMarketSummaryResponse\x12h\n" +
	"\x0fCalculateBasket\x12).nexcom.indices.v1.CalculateBasketRequest\x1a*.nexcom.indices.v1.CalculateBasketResponseB!Z\x1fgithub.com/nexcom/indices/protob\x06proto3"

var (
	file_proto_indices_proto_rawDescOnce sync.Once
	file_proto_indices_proto_rawDescData []byte
)

func file_proto_indices_proto_rawDescGZIP() []byte {
	file_proto_indices_proto_rawDescOnce.Do(func() {
		file_proto_indices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_indices_proto_rawDesc), len(file_proto_indices_proto_rawDesc)))
	})
	return file_proto_indices_proto_rawDescData
}

var file_proto_indices_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_indices_proto_goTypes = []any{
	(*Index)(nil),                     // 0: nexcom.indices.v1.Index
	(*CommodityPrice)(nil),            // 1: nexcom.indices.v1.CommodityPrice
	(*HistoricalDataPoint)(nil),       // 2: nexcom.indices.v1.HistoricalDataPoint
	(*IndexUpdate)(nil),               // 3: nexcom.indices.v1.IndexUpdate
	(*BasketComponent)(nil),           // 4: nexcom.indices.v1.BasketComponent
	(*MarketSummaryItem)(nil),         // 5: nexcom.indices.v1.MarketSummaryItem
	(*GetIndexRequest)(nil),           // 6: nexcom.indices.v1.GetIndexRequest
	(*GetIndexResponse)(nil),          // 7: nexcom.indices.v1.GetIndexResponse
	(*GetAllIndicesRequest)(nil),      // 8: nexcom.indices.v1.GetAllIndicesRequest
	(*GetAllIndicesResponse)(nil),     // 9: nexcom.indices.v1.GetAllIndicesResponse
	(*GetIndexHistoryRequest)(nil),    // 10: nexcom.indices.v1.GetIndexHistoryRequest
	(*GetIndexHistoryResponse)(nil),   // 11: nexcom.indices.v1.GetIndexHistoryResponse
	(*StreamIndexRequest)(nil),        // 12: nexcom.indices.v1.StreamIndexRequest
	(*GetCommodityPriceRequest)(nil),  // 13: nexcom.indices.v1.GetCommodityPriceRequest
	(*GetCommodityPriceResponse)(nil), // 14: nexcom.indices.v1.GetCommodityPriceResponse
	(*GetMarketSummaryRequest)(nil),   // 15: nexcom.indices.v1.GetMarketSummaryRequest
	(*GetMarketSummaryResponse)(nil),  // 16: nexcom.indices.v1.GetMarketSummaryResponse
	(*CalculateBasketRequest)(nil),    // 17: nexcom.indices.v1.CalculateBasketRequest
	(*CalculateBasketResponse)(nil),   // 18: nexcom.indices.v1.CalculateBasketResponse
}
var file_proto_indices_proto_depIdxs = []int32{
	0,  // 0: nexcom.indices.v1.GetIndexResponse.index:type_name -> nexcom.indices.v1.Index
	0,  // 1: nexcom.indices.v1.GetAllIndicesResponse.indices:type_name -> nexcom.indices.v1.Index
	2,  // 2: nexcom.indices.v1.GetIndexHistoryResponse.data:type_name -> nexcom.indices.v1.HistoricalDataPoint
	1,  // 3: nexcom.indices.v1.GetCommodityPriceResponse.price:type_name -> nexcom.indices.v1.CommodityPrice
	5,  // 4: nexcom.indices.v1.GetMarketSummaryResponse.items:type_name -> nexcom.indices.v1.MarketSummaryItem
	4,  // 5: nexcom.indices.v1.CalculateBasketRequest.components:type_name -> nexcom.indices.v1.BasketComponent
	4,  // 6: nexcom.indices.v1.CalculateBasketResponse.components:type_name -> nexcom.indices.v1.BasketComponent
	6,  // 7: nexcom.indices.v1.CommodityIndicesService.GetIndex:input_type -> nexcom.indices.v1.GetIndexRequest
	8,  // 8: nexcom.indices.v1.CommodityIndicesService.GetAllIndices:input_type -> nexcom.indices.v1.GetAllIndicesRequest
	10, // 9: nexcom.indices.v1.CommodityIndicesService.GetIndexHistory:input_type -> nexcom.indices.v1.GetIndexHistoryRequest
	12, // 10: nexcom.indices.v1.CommodityIndicesService.StreamIndex:input_type -> nexcom.indices.v1.StreamIndexRequest
	13, // 11: nexcom.indices.v1.CommodityIndicesService.GetCommodityPrice:input_type -> nexcom.indices.v1.GetCommodityPriceRequest
	15, // 12: nexcom.indices.v1.CommodityIndicesService.GetMarketSummary:input_type -> nexcom.indices.v1.GetMarketSummaryRequest
	17, // 13: nexcom.indices.v1.CommodityIndicesService.CalculateBasket:input_type -> nexcom.indices.v1.CalculateBasketRequest
	7,  // 14: nexcom.indices.v1.CommodityIndicesService.GetIndex:output_type -> nexcom.indices.v1.GetIndexResponse
	9,  // 15: nexcom.indices.v1.CommodityIndicesService.GetAllIndices:output_type -> nexcom.indices.v1.GetAllIndicesResponse
	11, // 16: nexcom.indices.v1.CommodityIndicesService.GetIndexHistory:output_type -> nexcom.indices.v1.GetIndexHistoryResponse
	3,  // 17: nexcom.indices.v1.CommodityIndicesService.StreamIndex:output_type -> nexcom.indices.v1.IndexUpdate
	14, // 18: nexcom.indices.v1.CommodityIndicesService.GetCommodityPrice:output_type -> nexcom.indices.v1.GetCommodityPriceResponse
	16, // 19: nexcom.indices.v1.CommodityIndicesService.GetMarketSummary:output_type -> nexcom.indices.v1.GetMarketSummaryResponse
	18, // 20: nexcom.indices.v1.CommodityIndicesService.CalculateBasket:output_type -> nexcom.indices.v1.CalculateBasketResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_indices_proto_init() }
func file_proto_indices_proto_init() {
	if File_proto_indices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_indices_proto_rawDesc), len(file_proto_indices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_indices_proto_goTypes,
		DependencyIndexes: file_proto_indices_proto_depIdxs,
		MessageInfos:      file_proto_indices_proto_msgTypes,
	}.Build()
	File_proto_indices_proto = out.File
	file_proto_indices_proto_goTypes = nil
	file_proto_indices_proto_depIdxs = nil
}
