apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: aml-flag-created-subscription
spec:
  pubsubname: nexcom-pubsub
  topic: aml.flag.created
  route: /aml-flag-created
scopes:
  - aml-alert-subscriber
